#!/usr/bin/env bash
# Generate the submission Dockerfile for an engine/vllm commit: FROM the organizer's vLLM image,
# then the apply script from make_apply.py (base-hash check -> patch --fuzz=0 -> commit-hash check
# -> py_compile) on /usr/local/lib/python3.12/dist-packages. Nothing is built here.
#   scripts/vllm/build_image.sh <commit> [--name lh-img:<mmdd>v] [--project-id 4727808]
# Output: build/scratch/vllm-image/Dockerfile (+ apply.sh). The platform builds inline Dockerfiles
# of at most 64 KiB with no build context, so everything travels inside the RUN line.
set -euo pipefail
cd "$(dirname "$0")/../.."
FROM_IMAGE=registry.dp.tech/dptech/dp/native/prod-20675/vllm-backport:260918-sm80
PKG=/usr/local/lib/python3.12/dist-packages
LIMIT=65536
NAME="lh-img:$(date -u +%m%d)v"   # image names/tags are visible to all arena members: keep them neutral
PROJECT_ID=4727808
COMMIT=${1:?commit required}; shift
while [ $# -gt 0 ]; do
  case $1 in
    --name) NAME=$2; shift 2 ;;
    --project-id) PROJECT_ID=$2; shift 2 ;;
    *) echo "unknown argument $1" >&2; exit 2 ;;
  esac
done
COMMIT=$(git rev-parse --verify "$COMMIT^{commit}")
OUT=build/scratch/vllm-image
mkdir -p "$OUT"
python3 scripts/vllm/make_apply.py "$COMMIT" -o "$OUT/apply.sh"
B64=$(base64 -w0 < "$OUT/apply.sh")
{
  echo "# engine/vllm $COMMIT on the organizer vLLM image; generated by scripts/vllm/build_image.sh"
  echo "FROM $FROM_IMAGE"
  echo "RUN set -eu; echo '$B64' | base64 -d > /tmp/ax-apply.sh; \\"
  echo "    sh /tmp/ax-apply.sh $PKG /usr/bin/python3; rm -f /tmp/ax-apply.sh; \\"
  echo "    mkdir -p /opt/ax; echo $COMMIT > /opt/ax/vllm_engine_commit"
} > "$OUT/Dockerfile"
SIZE=$(wc -c < "$OUT/Dockerfile")
echo "Dockerfile: $OUT/Dockerfile ($SIZE bytes, limit $LIMIT)"
[ "$SIZE" -le "$LIMIT" ] || { mv "$OUT/Dockerfile" "$OUT/Dockerfile.too-big"; echo "over the inline limit" >&2; exit 1; }
# The embedded script is byte-identical to the one the dev-box bundle runs.
sed -n "s/^RUN set -eu; echo '\([A-Za-z0-9+\/=]*\)' | base64 -d.*/\1/p" "$OUT/Dockerfile" | base64 -d | cmp - "$OUT/apply.sh"
echo "embedded apply script = $OUT/apply.sh (sha256 $(sha256sum < "$OUT/apply.sh" | cut -c1-16))"
echo
echo "Not built. To build and register:"
echo "  bohr image build --dockerfile $OUT/Dockerfile --name $NAME --project-id $PROJECT_ID --wait --yes -o json"
