#!/usr/bin/env python3
"""Write the shell script that applies an engine/vllm commit to an installed vllm package.

  scripts/vllm/make_apply.py <commit> -o apply.sh [--base vllm-base-backport-v0.13.1]

The generated script is used verbatim by the submission Dockerfile (build_image.sh) and by the
dev-box runtime bundle (bundle.sh), so both get the same bytes:

  sh apply.sh <dist-packages dir> <python3.12>

It carries the diff of engine/vllm/vllm/ between the base tag and the commit plus the SHA256
every touched file must have before (= base) and after (= commit). Any mismatch stops it: the
patch runs with --fuzz=0, and an image whose files differ from our base is refused instead of
patched approximately. Only Python files inside the vllm package can ship (the image holds the
installed package, not the source tree); changes elsewhere under engine/vllm (tests/, csrc/) are
listed and left out, and any other file type in vllm/ is refused.
"""

import argparse
import base64
import gzip
import hashlib
import subprocess
import sys

PREFIX = "engine/vllm/"
PACKAGE = "engine/vllm/vllm/"
MARKER = "vllm-0.13.1.dist-info/RECORD"  # present in the base image's dist-packages


def git(*args: str, binary: bool = False):
    out = subprocess.run(["git", *args], check=True, capture_output=True).stdout
    return out if binary else out.decode()


def blob_sha256(rev: str, path: str) -> str:
    return hashlib.sha256(git("show", f"{rev}:{path}", binary=True)).hexdigest()


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("commit")
    ap.add_argument("--base", default="vllm-base-backport-v0.13.1")
    ap.add_argument("-o", "--output", required=True)
    args = ap.parse_args()
    base = git("rev-parse", "--verify", f"{args.base}^{{commit}}").strip()
    commit = git("rev-parse", "--verify", f"{args.commit}^{{commit}}").strip()

    changes = [
        line.split("\t")
        for line in git(
            "diff", "--no-renames", "--name-status", base, commit, "--", PREFIX
        ).splitlines()
    ]
    shipped, skipped = [], []
    for status, path in changes:
        if not path.startswith(PACKAGE):
            skipped.append(path)
        elif path.endswith(".py"):
            shipped.append((status, path))
        else:
            sys.exit(f"refusing: {path} is not a Python file inside the vllm package")
    if not shipped:
        sys.exit("nothing to ship: the commit does not change engine/vllm/vllm/*.py")

    rel = lambda p: p[len(PREFIX):]  # path relative to dist-packages
    before = [(blob_sha256(base, p), rel(p)) for s, p in shipped if s != "A"]
    after = [(blob_sha256(commit, p), rel(p)) for s, p in shipped if s != "D"]
    added = [rel(p) for s, p in shipped if s == "A"]
    deleted = [rel(p) for s, p in shipped if s == "D"]
    diff = git(
        "diff", "--no-renames", "--no-color", "--full-index", base, commit, "--",
        *[p for _, p in shipped], binary=True,
    )
    payload = base64.b64encode(gzip.compress(diff, mtime=0)).decode()

    def sums(rows):
        return "\n".join(f"{h}  {p}" for h, p in rows)

    compiled = " ".join(p for _, p in after)
    lines = [
        "#!/bin/sh",
        f"# engine/vllm {args.base} ({base[:12]}) -> {commit}; generated by scripts/vllm/make_apply.py",
        '# usage: sh apply.sh <dist-packages dir> <python3.12>',
        "set -eu",
        'PKG=$1 PY=$2',
        'cd "$PKG"',
        f'test -f {MARKER} || {{ echo "not the base image package: {MARKER} missing" >&2; exit 1; }}',
        'T=$(mktemp -d)',
        "cat > \"$T/before\" <<'EOF'",
        sums(before),
        "EOF",
        "cat > \"$T/after\" <<'EOF'",
        sums(after),
        "EOF",
    ]
    if before:
        lines.append('sha256sum --quiet -c "$T/before" || { echo "installed files differ from the base" >&2; exit 1; }')
    for p in added:
        lines.append(f'test ! -e {p} || {{ echo "{p} already exists" >&2; exit 1; }}')
    lines += [
        f"echo '{payload}' | base64 -d | gunzip > \"$T/engine.diff\"",
        'patch -p3 --batch --forward --fuzz=0 --no-backup-if-mismatch -r - < "$T/engine.diff"',
    ]
    if after:
        lines.append('sha256sum --quiet -c "$T/after" || { echo "patched files differ from the commit" >&2; exit 1; }')
    for p in deleted:
        lines.append(f'test ! -e {p} || {{ echo "{p} was not removed" >&2; exit 1; }}')
    if compiled:
        lines.append(f'"$PY" -m py_compile {compiled}')
    lines += [
        'rm -rf "$T"',
        f'echo "engine/vllm {commit[:12]} applied: {len(shipped)} files"',
    ]
    with open(args.output, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"{args.output}: {len(shipped)} shipped files, {len(skipped)} left out "
          f"(outside vllm/: {', '.join(sorted(skipped)[:5])}{' ...' if len(skipped) > 5 else ''}), "
          f"diff {len(diff)} bytes -> payload {len(payload)} bytes")


if __name__ == "__main__":
    main()
